#!/usr/bin/env bash

set -eu

js_file=$1

TOOLS_DIR=$(cd "$PWD/$(dirname $0)"; pwd)
export NODE_PATH=$TOOLS_DIR/node_modules:.
cat <<EOF | node - "$js_file"
const escomplex = require('typhonjs-escomplex')

function cyc_complexity(func) {
    const complexities = escomplex.analyzeModule(func.toString())
    const cyc = complexities.methods[0].cyclomatic
    return cyc
}

const path = "$js_file"
const { fn } = require(path)
const cyc = cyc_complexity(fn)
console.log(cyc)

EOF
